import { FamilyTree } from "./types";

export const familyData: FamilyTree[] = [
    {
        id: '1',
        name: 'Maxwell',
        birthDate: '15 May 1945',
        image: '/icons/user.png',
        generation: 1,
        position: 1,
        color: '#d7f5ff',
        status: '1945-2020',
    },
    {
        id: '2',
        name: 'Patricia',
        birthDate: '23 Nov 1948',
        image: '/icons/user.png',
        generation: 1,
        position: 2,
        color: '#d7f5ff',
        status: '1948-2022',
    },


    {
        id: '3',
        name: 'Robert',
        birthDate: '12 Jun 1970',
        image: '/icons/user.png',
        generation: 2,
        position: 1,
        parentIds: ['1', '2'],
        color: '#d7f5ff',
        status: '1970',
    },
    {
        id: '4',
        name: 'Emily',
        birthDate: '5 Apr 1972',
        image: '/icons/user.png',
        generation: 2,
        position: 2,
        parentIds: ['1', '2'],
        color: '#d7f5ff',
        status: '1972',
    },
    {
        id: '5',
        name: 'Michael',
        birthDate: '18 Sep 1975',
        image: '/icons/user.png',
        generation: 2,
        position: 3,
        parentIds: ['1', '2'],
        color: '#e6ffea',
        status: '1975',
    },
    {
        id: '6',
        name: 'Jessica',
        birthDate: '3 Mar 1978',
        image: '/icons/user.png',
        generation: 2,
        position: 4,
        parentIds: ['1', '2'],
        color: '#e6ffea',
        status: '1978',
    },
    {
        id: '7',
        name: 'Jennifer',
        birthDate: '29 Jul 1980',
        image: '/icons/user.png',
        generation: 2,
        position: 5,
        parentIds: ['1', '2'],
        color: '#e6ffea',
        status: '1980',
    },
    {
        id: '8',
        name: 'Thomas',
        birthDate: '14 Feb 1982',
        image: '/icons/user.png',
        generation: 2,
        position: 6,
        parentIds: ['1', '2'],
        color: '#fff5e6',
        status: '1982',
    },
    {
        id: '9',
        name: 'David',
        birthDate: '7 Dec 1984',
        image: '/icons/user.png',
        generation: 2,
        position: 7,
        parentIds: ['1', '2'],
        color: '#fff5e6',
        status: '1984',
    },
    {
        id: '10',
        name: 'Richard',
        birthDate: '22 Oct 1986',
        image: '/icons/user.png',
        generation: 2,
        position: 8,
        parentIds: ['1', '2'],
        color: '#fff5e6',
        status: '1986',
    },


    {
        id: '11',
        name: 'Everett',
        birthDate: '21 Mar 2000',
        image: '/icons/user.png',
        generation: 3,
        position: 1,
        parentIds: ['3'],
        color: '#e6ffea',
        status: '2000',
    },
    {
        id: '12',
        name: 'Evelyn',
        birthDate: '9 Sep 2001',
        image: '/icons/user.png',
        generation: 3,
        position: 2,
        parentIds: ['4'],
        color: '#e6ffea',
        status: '2001',
    },
    {
        id: '13',
        name: 'Jack',
        birthDate: '4 May 2002',
        image: '/icons/user.png',
        generation: 3,
        position: 3,
        parentIds: ['5'],
        color: '#e6ffea',
        status: '2002',
    },
    {
        id: '14',
        name: 'Conrad',
        birthDate: '27 Dec 2003',
        image: '/icons/user.png',
        generation: 3,
        position: 4,
        parentIds: ['6'],
        color: '#e6ffea',
        status: '2003',
    },
    {
        id: '15',
        name: 'Katherine',
        birthDate: '6 Aug 2004',
        image: '/icons/user.png',
        generation: 3,
        position: 5,
        parentIds: ['7'],
        color: '#e6ffea',
        status: '2004',
    },
    {
        id: '16',
        name: 'Martin',
        birthDate: '13 Jun 2005',
        image: '/icons/user.png',
        generation: 3,
        position: 6,
        parentIds: ['9'],
        color: '#fff5e6',
        status: '2005',
    },
    {
        id: '17',
        name: 'Gabriel',
        birthDate: '13 Jun 2006',
        image: '/icons/user.png',
        generation: 3,
        position: 7,
        parentIds: ['10'],
        color: '#fff5e6',
        status: '2006',
    },
    {
        id: '18',
        name: 'Emma',
        birthDate: '15 Apr 2008',
        image: '/icons/user.png',
        generation: 3,
        position: 8,
        parentIds: ['4'],
        color: '#fff5e6',
        status: '2008',
    },
]