export const videos = [
    {
        id: "1",
        title: "James Carter",
        description: "Growing Up in the South: A Boy's Journey Through Change",
        duration: "12:00 min",
        thumbnail: "/image.png",
        videoUrl: "/268528_tiny.mp4",
    },
    {
        id: "2",
        title: "James Carter",
        description: "Growing Up in the South: A Boy's Journey Through Change",
        duration: "12:00 min",
        thumbnail: "/image.png",
        videoUrl: "/268528_tiny.mp4",
    },
    {
        id: "3",
        title: "James Carter",
        description: "Growing Up in the South: A Boy's Journey Through Change",
        duration: "12:00 min",
        thumbnail: "/image.png",
        videoUrl: "/268528_tiny.mp4",
    },
    {
        id: "4",
        title: "James Carter",
        description: "Growing Up in the South: A Boy's Journey Through Change",
        duration: "12:00 min",
        thumbnail: "/image.png",
        videoUrl: "/268528_tiny.mp4",
    },
    {
        id: "5",
        title: "James Carter",
        description: "Growing Up in the South: A Boy's Journey Through Change",
        duration: "12:00 min",
        thumbnail: "/image.png",
        videoUrl: "/268528_tiny.mp4",
    },
    {
        id: "6",
        title: "James Carter",
        description: "Growing Up in the South: A Boy's Journey Through Change",
        duration: "12:00 min",
        thumbnail: "/image.png",
        videoUrl: "/268528_tiny.mp4",
    },
    {
        id: "7",
        title: "James Carter",
        description: "Growing Up in the South: A Boy's Journey Through Change",
        duration: "12:00 min",
        thumbnail: "/image.png",
        videoUrl: "/268528_tiny.mp4",
    },
    {
        id: "8",
        title: "James Carter",
        description: "Growing Up in the South: A Boy's Journey Through Change",
        duration: "12:00 min",
        thumbnail: "/image.png",
        videoUrl: "/268528_tiny.mp4",
    },
    {
        id: "9",
        title: "James Carter",
        description: "Growing Up in the South: A Boy's Journey Through Change",
        duration: "12:00 min",
        thumbnail: "/image.png",
        videoUrl: "/268528_tiny.mp4",
    },
]